### ISSUE TITLE
Initial setup

### ISSUE THREAD

**Issue by antoniojgage** [pagevanhoy/pagevanhoy.github.io#1]
Everything is looking pretty good so far. Only a few suggestions so far with what exists:

1. You should have an assets folder that holds everything that is not an HTML file (for now)
assets/css
assets/images
assets/misc

1. be sure to link the javascript for Bootstrap under your body tag. Generally, you will need this. 

For an extra challenge try to FIRST create a branch to handle these changes with the steps discussed in slack (listed below)

1. create a branch from master
1. Change only 1 specific task
1. commit (however many it takes)
1. open a pull request pointed to the base master
1. send a technical lead/peer the PR number or tag them in the PR
once approved merge into master

**Comment by steppinonland** [comment]
thank you antonio!!!!! 
![takingnotes](https://user-images.githubusercontent.com/58382657/80287067-e75d1200-86f4-11ea-817e-1c3bf9ab94cc.gif)

**Comment by pagevanhoy** [comment]
Bootstrap JavaScript link should be placed under body and not in the head?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
