### ISSUE TITLE
Wireframe check

### ISSUE THREAD

**Issue by pagevanhoy** [pagevanhoy/pagevanhoy.github.io#2]
Please review the wireframe in the image folder - screenshot.  I have included all three web pages, each color is one container.

**Comment by steppinonland** [comment]
hey! i took a look at your wireframe. I like it! it looks great so far. keep it up!!!

**Comment by pagevanhoy** [comment]
Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
